# -*- coding: utf-8 -*-
"""Untitled25.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AIVZnc-X68qmEfrNdjtrxmAx2xa3u2wm
"""

!pip install transformers torch sentencepiece rouge-score bert-score sumy numpy pandas scikit-learn openpyxl

import time
import tracemalloc
import numpy as np
import pandas as pd
import torch

from transformers import pipeline
from rouge_score import rouge_scorer
from bert_score import score as bert_score

from sumy.parsers.plaintext import PlaintextParser
from sumy.nlp.tokenizers import Tokenizer
from sumy.summarizers.lex_rank import LexRankSummarizer
from sumy.summarizers.text_rank import TextRankSummarizer

dataset = [
    {
        "text": "Google introduced a new AI model designed to improve reasoning and reduce hallucinations across its products.",
        "reference": "Google launched a new AI model to improve reasoning and reduce hallucinations."
    },
    {
        "text": "ISRO successfully launched a weather satellite to enhance climate monitoring across India.",
        "reference": "ISRO launched a satellite to improve climate monitoring."
    },
    {
        "text": "The stock market reacted positively after the central bank announced interest rate cuts.",
        "reference": "Markets rose after the central bank cut interest rates."
    }
]

texts = [d["text"] for d in dataset]
refs  = [d["reference"] for d in dataset]

rouge = rouge_scorer.RougeScorer(
    ["rouge1", "rouge2", "rougeL"], use_stemmer=True
)

def compute_rouge(preds, refs):
    r1 = r2 = rl = 0.0
    for p, r in zip(preds, refs):
        s = rouge.score(r, p)
        r1 += s["rouge1"].fmeasure
        r2 += s["rouge2"].fmeasure
        rl += s["rougeL"].fmeasure
    n = len(preds)
    return r1/n, r2/n, rl/n

def compute_bertscore(preds, refs):
    _, _, f1 = bert_score(preds, refs, lang="en", device="cuda")
    return f1.mean().item()

from transformers import AutoTokenizer, AutoModelForSeq2SeqLM, AutoModelForCausalLM

device = "cuda" if torch.cuda.is_available() else "cpu"

# BART
bart_tokenizer = AutoTokenizer.from_pretrained("facebook/bart-large-cnn")
bart_model = AutoModelForSeq2SeqLM.from_pretrained("facebook/bart-large-cnn").to(device)

# T5
t5_tokenizer = AutoTokenizer.from_pretrained("t5-small")
t5_model = AutoModelForSeq2SeqLM.from_pretrained("t5-small").to(device)

# Pegasus
pegasus_tokenizer = AutoTokenizer.from_pretrained("google/pegasus-xsum")
pegasus_model = AutoModelForSeq2SeqLM.from_pretrained("google/pegasus-xsum").to(device)

# GPT-2 (baseline)
gpt2_tokenizer = AutoTokenizer.from_pretrained("gpt2")
gpt2_model = AutoModelForCausalLM.from_pretrained("gpt2").to(device)

def run_bart(texts):
    summaries = []
    for t in texts:
        inputs = bart_tokenizer(t, return_tensors="pt", truncation=True).to(device)
        output = bart_model.generate(**inputs, max_length=60)
        summaries.append(bart_tokenizer.decode(output[0], skip_special_tokens=True))
    return summaries

def run_t5(texts):
    summaries = []
    for t in texts:
        inputs = t5_tokenizer("summarize: " + t, return_tensors="pt", truncation=True).to(device)
        output = t5_model.generate(**inputs, max_length=60)
        summaries.append(t5_tokenizer.decode(output[0], skip_special_tokens=True))
    return summaries

def run_pegasus(texts):
    summaries = []
    for t in texts:
        inputs = pegasus_tokenizer(t, return_tensors="pt", truncation=True).to(device)
        output = pegasus_model.generate(**inputs, max_length=60)
        summaries.append(pegasus_tokenizer.decode(output[0], skip_special_tokens=True))
    return summaries

def run_gpt2(texts):
    summaries = []
    for t in texts:
        inputs = gpt2_tokenizer(t, return_tensors="pt", truncation=True).to(device)
        output = gpt2_model.generate(**inputs, max_length=60)
        summaries.append(gpt2_tokenizer.decode(output[0], skip_special_tokens=True))
    return summaries

def run_sumy_lexrank(texts):
    summaries = []
    for t in texts:
        parser = PlaintextParser.from_string(t, Tokenizer("english"))
        summarizer = LexRankSummarizer()
        summary = summarizer(parser.document, 2)
        summaries.append(" ".join(str(s) for s in summary))
    return summaries

def run_sumy_textrank(texts):
    summaries = []
    for t in texts:
        parser = PlaintextParser.from_string(t, Tokenizer("english"))
        summarizer = TextRankSummarizer()
        summary = summarizer(parser.document, 2)
        summaries.append(" ".join(str(s) for s in summary))
    return summaries

import nltk
nltk.download("punkt")
nltk.download("punkt_tab")

MODELS = {
    "BART": run_bart,
    "T5": run_t5,
    "Pegasus": run_pegasus,
    "GPT-2": run_gpt2,
    "Sumy-LexRank": run_sumy_lexrank,
    "Sumy-TextRank": run_sumy_textrank
}

records = []

for name, fn in MODELS.items():
    print(f"Running {name}...")

    torch.cuda.reset_peak_memory_stats()
    tracemalloc.start()
    start = time.perf_counter()

    preds = fn(texts)

    elapsed = time.perf_counter() - start
    tracemalloc.stop()

    gpu_mem = torch.cuda.max_memory_allocated() / (1024 ** 2)

    r1, r2, rl = compute_rouge(preds, refs)
    bert_f1 = compute_bertscore(preds, refs)

    records.append({
        "Model": name,
        "ROUGE-1": r1,
        "ROUGE-2": r2,
        "ROUGE-L": rl,
        "BERTScore": bert_f1,
        "Inference Time (s)": elapsed,
        "Peak Memory (MB)": gpu_mem
    })

def topsis(df, weights, benefit_idx):
    X = df.values.astype(float)
    X = X / np.sqrt((X ** 2).sum(axis=0))
    X = X * weights

    best = np.max(X[:, benefit_idx], axis=0)
    worst = np.min(X[:, benefit_idx], axis=0)

    s_pos = np.linalg.norm(X[:, benefit_idx] - best, axis=1)
    s_neg = np.linalg.norm(X[:, benefit_idx] - worst, axis=1)

    return s_neg / (s_pos + s_neg)

df = pd.DataFrame(records)

criteria = [
    "ROUGE-1", "ROUGE-2", "ROUGE-L",
    "BERTScore", "Inference Time (s)", "Peak Memory (MB)"
]

WEIGHT_CONFIGS = {
    "Balanced":        [0.25, 0.15, 0.15, 0.20, 0.15, 0.10],
    "Quality-Priority":[0.35, 0.20, 0.20, 0.20, 0.03, 0.02],
    "Speed-Priority":  [0.05, 0.05, 0.05, 0.10, 0.45, 0.30]
}

for name, w in WEIGHT_CONFIGS.items():
    w = np.array(w)
    w = w / w.sum()
    df[name] = topsis(df[criteria], w, benefit_idx=[0,1,2,3])

df["Best Rank"] = df[list(WEIGHT_CONFIGS.keys())].idxmax(axis=1)
df = df.sort_values("Balanced", ascending=False)

df.to_excel("summarization_topsis_results.xlsx", index=False)
df

import matplotlib.pyplot as plt
plt.figure(figsize=(10,5))
plt.bar(df["Model"], df["Balanced"])
plt.xlabel("Summarization Model")
plt.ylabel("TOPSIS Score (Balanced)")
plt.title("TOPSIS Ranking of Text Summarization Models (Balanced Scenario)")
plt.xticks(rotation=30)
plt.tight_layout()
plt.show()

